// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Token(token string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Token_a287`,
		Function: `function __templ_Token_a287(token){document.body.addEventListener("htmx:configRequest", (event) => {
    event.detail.headers["X-CSRF-Token"] = token;
  });
  console.log(token);}`,
		Call:       templ.SafeScript(`__templ_Token_a287`, token),
		CallInline: templ.SafeScriptInline(`__templ_Token_a287`, token),
	}
}

// if (event.detail["verb"] !== "get") {
//   event.detail.unfilteredParameters["csrf"] =  token ;
// }
