// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Token(t string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = tokenScript(t).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func tokenScript(t string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_tokenScript_2d56`,
		Function: `function __templ_tokenScript_2d56(t){document.body.addEventListener("htmx:configRequest", (event) => {
    event.detail.headers["X-CSRF-Token"] = t;
  });}`,
		Call:       templ.SafeScript(`__templ_tokenScript_2d56`, t),
		CallInline: templ.SafeScriptInline(`__templ_tokenScript_2d56`, t),
	}
}

// script TooTest(s string) {
//   console.log(s);
// }

// templ Union(token, s string) {
// 	@Token(token)
// 	@TooTest(s)
// }

// if (event.detail["verb"] !== "get") {
//   event.detail.unfilteredParameters["csrf"] =  token ;
// }
